# Generated by Django 6.0.3 on 2026-03-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_financialrecord_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='category',
            field=models.CharField(choices=[('servico', 'Serviço'), ('produto', 'Produto'), ('outro', 'Outro'), ('salario', 'Salário'), ('aluguel', 'Aluguel'), ('energia', 'Energia'), ('agua', 'Água'), ('telefone', 'Telefone'), ('manutencao', 'Manutenção'), ('marketing', 'Marketing'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('boleto', 'Boleto'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro')], max_length=20, null=True),
        ),
    ]
