# Generated by Django 6.0.3 on 2026-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_product_price"),
    ]

    operations = [
        # Adicionar horários de funcionamento para clínicas
        migrations.AddField(
            model_name="clinic",
            name="opening_time",
            field=models.TimeField(default="08:00", help_text="Horário de abertura"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="closing_time",
            field=models.TimeField(default="20:00", help_text="Horário de fechamento"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="appointment_interval",
            field=models.IntegerField(
                default=30, help_text="Intervalo médio entre atendimentos (minutos)"
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="work_days",
            field=models.CharField(
                max_length=20,
                default="seg-sex",
                help_text="Dias de funcionamento (ex: seg-sex, seg-sab)",
            ),
        ),
        # Melhorar estrutura de serviços com categoria pai
        migrations.AddField(
            model_name="service",
            name="parent_category",
            field=models.CharField(
                max_length=50,
                null=True,
                blank=True,
                help_text="Categoria pai do serviço (ex: Higiene, Veterinária)",
            ),
        ),
        # Padronizar campos de pets
        migrations.AlterField(
            model_name="pet",
            name="species",
            field=models.CharField(
                max_length=30,
                choices=[
                    ("cachorro", "Cachorro"),
                    ("gato", "Gato"),
                    ("passaro", "Pássaro"),
                    ("roedor", "Roedor"),
                    ("outro", "Outro"),
                ],
                default="cachorro",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="standard_breed",
            field=models.CharField(
                max_length=50,
                null=True,
                blank=True,
                help_text="Raça padronizada baseada na espécie",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="color",
            field=models.CharField(
                max_length=30,
                choices=[
                    ("preto", "Preto"),
                    ("branco", "Branco"),
                    ("cinza", "Cinza"),
                    ("marrom", "Marrom"),
                    ("bege", "Bege"),
                    ("dourado", "Dourado"),
                    ("rajado", "Rajado"),
                    ("malhado", "Malhado"),
                    ("outro", "Outro"),
                ],
                null=True,
                blank=True,
            ),
        ),
        # Padronizar funcionários com cargos pré-definidos
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                max_length=30,
                choices=[
                    ("veterinario", "Veterinário"),
                    ("atendente", "Atendente"),
                    ("tosador", "Tosador"),
                    ("auxiliar", "Auxiliar"),
                    ("gerente", "Gerente"),
                ],
                default="atendente",
            ),
        ),
        # Melhorar produtos com alertas de estoque
        migrations.AddField(
            model_name="product",
            name="alert_threshold",
            field=models.IntegerField(
                default=10, help_text="Quantidade para alerta de estoque baixo"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Produto ativo"),
        ),
        # Padronizar estados das clínicas
        migrations.AlterField(
            model_name="clinic",
            name="state",
            field=models.CharField(
                max_length=2,
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                null=True,
                blank=True,
            ),
        ),
    ]
