# Generated by Django 6.0.3 on 2026-03-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_business_hours_and_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, help_text='Raça personalizada', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='standard_breed',
            field=models.CharField(blank=True, choices=[('labrador', 'Labrador'), ('golden', 'Golden Retriever'), ('poodle', 'Poodle'), ('bulldog', 'Bulldog'), ('pastor_alemao', 'Pastor Alemão'), ('beagle', 'Beagle'), ('chihuahua', 'Chihuahua'), ('yorkshire', 'Yorkshire'), ('shih_tzu', 'Shih Tzu'), ('rottweiler', 'Rottweiler'), ('pitbull', 'Pitbull'), ('srd', 'Sem Raça Definida (SRD)'), ('siames', 'Siamês'), ('persa', 'Persa'), ('maine_coon', 'Maine Coon'), ('angora', 'Angorá'), ('sphynx', 'Sphynx'), ('ragdoll', 'Ragdoll'), ('bengal', 'Bengal'), ('british_shorthair', 'British Shorthair'), ('outro', 'Outro')], help_text='Raça padronizada', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('medicamento', 'Medicamento'), ('higiene', 'Higiene'), ('acessorio', 'Acessório'), ('racao', 'Ração'), ('brinquedo', 'Brinquedo'), ('outro', 'Outro')], default='outro', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('veterinaria', 'Veterinária'), ('tosa', 'Tosa'), ('banho', 'Banho'), ('higiene', 'Higiene'), ('exame', 'Exame'), ('vacina', 'Vacina'), ('cirurgia', 'Cirurgia'), ('outro', 'Outro')], default='outro', max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duração estimada em minutos', null=True),
        ),
    ]
